source:
  rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
keys:
  - suitcase
  - person
street:
  xx街道
interval:
  10
device:
  cpu
report_url:
  https://longgang.yoyoyard.com/api/v1/events